### ISSUE TITLE
Сборка библиотеки.

### ISSUE THREAD

**Issue by stallman** [fuCtor/QAMQP#1]
При сборке были проблемы. Удалил некоторые связки - вроде скомпилировалось. Однако осталась проблема при запуске тестового приложения (qamqp). Выходит сообщение 'Cannot mix incompatible Qt libraries'.
Не могли бы вы подсказать в чем проблема ?
Использую qt4.6.3/linux/gcc4.4.7

**Comment by fuCtor** [comment]
Какие именно связки были удалены?
Код писался под windows и там в наличии были приватные заголовочные файлы Qt, которые как оказалось лучше никак не использовать. Сегодня/завтра перепишу без их использования и должен код заработать. Приношу свои извинения.

**Comment by stallman** [comment]
Приватные классы я добавил в проект ( взял из сорцов) Однако
скомпилированная часть осталась из дистрибутива.
Удалил

amqp.cpp
13 -- struct QAMQP::
13 ++ struct /_QAMQP::_/

amqp_frame.cpp
374 -- QAMQP::Frame::decimal v(value.valueQAMQP::Frame::decimal());
375 -- s << v.scale;
376 -- s << v.value;

В qt 4.6 нет QDateTime::fromMSecsSinceEpoch - поменял на fromTime_t

А для чего собственно используются приватные файлы ? Можно как-то было
обойти их использование.

17.04.12, fuCtorreply@reply.github.com
написал(а):

**Comment by fuCtor** [comment]
Захотелось в стиле Qt написать, скрыв реализацию, получилось довольно удобно, но есть другая реализация, без использования приватных классов из Qt. Вот с помощью нее и перепишу. Тогда зависимости такой не будет, а интерфейсная сторона останется прежней.

В целом код сырой еще, планирую его доделывать, т.к. потом собираюсь включить в программу, над которой в основном работаю.

**Comment by stallman** [comment]
Спасибо. Буду очень благодарен.
А то си-реализация жутко не понравилась.

**Comment by fuCtor** [comment]
Готово, убрал зависимость. Теперь должно без проблем собираться. Си реализации видел, в контексте Qt очень не удобно использовать, собственно это и заставило начать разбирать протокол самому.

**Comment by stallman** [comment]
Супер ! Буду пробовать )

**Comment by fuCtor** [comment]
Если все будет работать, отпишитесь, закрою Issue.

**Comment by stallman** [comment]
Работает, с учетом поправок которые писал выше.

**Comment by stallman** [comment]
Спасибо.

**Comment by fuCtor** [comment]
Да не за что, будут замечания предложения, буду рад услышать. Особенно в плане ошибок, качества кода и тд.

Тестировал на передачу файлов, с файлами в 30мб справлялся без проблем. Более серьезных проверок не проводил. Надо еще на утечки провериться (но не должно быть).
