### ISSUE TITLE
Do you plan use Qt5?

### ISSUE THREAD

**Issue by lissdx** [fuCtor/QAMQP#11]
Hi.
Just amazing library.
Thank you. I have a question :).
Do you plan use Qt5 for this library?

**Comment by fuCtor** [comment]
Yes of course, I think that in this month Qt5 support  will be implemented.

**Comment by lissdx** [comment]
O :) nice. Thank you. I am waiting :)

**Comment by fuCtor** [comment]
You can try use this branch: https://github.com/fuCtor/QAMQP/tree/qt5
