### ISSUE TITLE
Exchange usage & binded signal

### ISSUE THREAD

**Issue by kluthen** [fuCtor/QAMQP#12]
Hello again !

I had some trouble with Exchange and binding them to queues, most of it was solved by delaying the whole process with extensive usage of signal and slots since declaration and binding are async. 

Though there is one exception that i ran through, Exchange says it can send a "binded" signal.
I happend to expect it to send me the signal when the exchange was bound to the given queue, but since at the moment, bind on an exchange uses the queue binding function, the "binded" signal of the exchange never get send. (I havent tried yet to use the queue binded(bool) signal, will do so in a few minutes)

This is a minor glitch, just wanted to share ;)

Thanks for your good job !

**Comment by fuCtor** [comment]
Hello!

Yep =) It's my mistake. I review specs. Only queue can emit binded signal.

It has fixed. Thank you.

**Comment by kluthen** [comment]
Thanks you !

Indeed using the queue's signal made it work
