### ISSUE TITLE
 About Network disconnected then to re-connect again!

### ISSUE THREAD

**Issue by ximply** [fuCtor/QAMQP#17]
Today I tested the QAMQP Client as follows:

Step 1>>
Start the QAMQP Client, when it connected to the MQ Server then unplug the network cable. Now just wait about 10 minutes(heartbeat is 600 seconds) to get the disconnection from MQ Server. But 10 minutes later, the QAMQP Client cannot connect to the MQ Server.

Step 2>>
So I add a timer to class  QAMQP::Network

// in the amqp_network.h
private:
    int m_nHeartBeatTimer;
public:
    void startHeartBeatTimer();
protected:
    void timerEvent(QTimerEvent *pEvent);

// in the amqp_network.cpp
QAMQP::Network::Network( QObject \* parent /_= 0_/ ):QObject(parent)
{
    qRegisterMetaTypeQAMQP::Frame::Method("QAMQP::Frame::Method");

```
buffer_ = new QBuffer(this);
offsetBuf = 0;
leftSize = 0;
timeOut_ = 1000;
connect_ = false;

              m_nHeartBeatTimer = 0; // add by me

buffer_->open(QIODevice::ReadWrite);

initSocket(false);
```

}

void QAMQP::Network::startHeartBeatTimer()
{
    if (m_nHeartBeatTimer == 0)
    {
        m_nHeartBeatTimer = this->startTimer(s_nHeartBeatIntval);
    }
}

void QAMQP::Network::timerEvent(QTimerEvent *pEvent)
{
    if (pEvent->timerId() == m_nHeartBeatTimer)
    {
        if (socket_)
        {
            if (socket_->state() == QAbstractSocket::UnconnectedState)
            {
                connectTo();
            }
        }
    }
    else
    {
        QObject::timerEvent(pEvent);
    }
}

// in the amqp_p.h
public:
    void startHeartBeatTimer();
// in the amqp.cpp
void ClientPrivate::startHeartBeatTimer()
{
    network_->startHeartBeatTimer();
}

// in the amqp.h
public:
    void startHeartBeatTimer();
// in the amqp.cpp
void QAMQP::Client::startHeartBeatTimer()
{
    pd_func()->startHeartBeatTimer();
}

// in the test.cpp, append startHeartBeatTimer after client open
client_->open(con);
client_->startHeartBeatTimer();

Summary >> 
As a result, it works! And do you have other solutions?

**Comment by fuCtor** [comment]
void QAMQP::Network::error( QAbstractSocket::SocketError socketError )
{
if(timeOut_ == 0)
{
timeOut_ = 1000;
} else {  
if(timeOut_ < 120000)
{
timeOut_ *= 5;
}
}

Q_UNUSED(socketError);
switch(socketError)
{
case QAbstractSocket::ConnectionRefusedError:
case QAbstractSocket::RemoteHostClosedError:
case QAbstractSocket::SocketTimeoutError:
case QAbstractSocket::NetworkError:
case QAbstractSocket::ProxyConnectionClosedError:
case QAbstractSocket::ProxyConnectionRefusedError:
case QAbstractSocket::ProxyConnectionTimeoutError:

default:
qWarning() << "AMQP Socket Error: " << socket_->errorString();
break;
}

if( autoReconnect_ && connect_ )
{
QTimer::singleShot(timeOut_, this, SLOT(connectTo()));
}

}

This code must reconnect, but i think after 10 minutes polling interval is about 2 minutes. Maybe top limit must by changed.
