### ISSUE TITLE
does not compile on Qt without SSL support

### ISSUE THREAD

**Issue by thefastman** [fuCtor/QAMQP#18]
Maybe will be better to add some _NO_SSL_ define to avoid this issue.
Custom Qt5 build without SSL support makes impossible to build a project:

1>src\qamqp\amqp_network.cpp(38): error C2061: syntax error : identifier 'QSslSocket'
1>src\qamqp\amqp_network.cpp(183): error C2061: syntax error : identifier 'QSslSocket'
1>src\qamqp\amqp_network.cpp(184): error C2065: 'QSslSocket' : undeclared identifier
1>src\qamqp\amqp_network.cpp(184): error C2065: 'ssl_' : undeclared identifier
1>src\qamqp\amqp_network.cpp(184): error C2061: syntax error : identifier 'QSslSocket'
1>src\qamqp\amqp_network.cpp(185): error C2065: 'ssl_' : undeclared identifier
1>src\qamqp\amqp_network.cpp(185): error C2227: left of '->setProtocol' must point to class/struct/union/generic type
1>          type is ''unknown-type''
1>src\qamqp\amqp_network.cpp(204): error C2061: syntax error : identifier 'QSslSocket'

**Comment by fuCtor** [comment]
Fixed.
Add QT_NO_SSL and some warning message if will be try amqps using.
