### ISSUE TITLE
Hearbet doesn't work properly

### ISSUE THREAD

**Issue by thefastman** [fuCtor/QAMQP#19]
After re-connection, consumer stops receiving messages.
How to reproduce:
- start consumer
- try to send messages (OK)
- sudo service rabbitmq-server stop
- sudo service rabbitmq-server start
- wait when consumer restore connection
- try to send message (FAIL)

**Comment by fuCtor** [comment]
Can you show code sample?

**Comment by thefastman** [comment]
Hi, yes.

``` cpp
void CWorkerThread::_doWork()
{
    initConsumer();
}

bool CWorkerThread::initConsumer()
{
    m_pConsumer = new Client(this);
    m_pConsumer->setAutoReconnect(true);
    m_pConsumer->open(QUrl(m_cConnectionString)); 

    m_pQueue = m_pConsumer->createQueue();
    m_pQueue->setNoAck(false);

    connect(m_pQueue, SIGNAL(declared())       , this, SLOT(_declared()));
    connect(m_pQueue, SIGNAL(messageReceived()), this, SLOT(_message()));

    m_pQueue->setConsumerTag(m_cRouteTag);
    m_pQueue->declare("kf.scenechange", Queue::Durable); 

    return true;
}

void CWorkerThread::_declared()
{
    qDebug() << "declared() called...";
    m_pQueue->setQOS(0, 1);
    m_pQueue->consume();
}

void CWorkerThread::_message()
{
    while (m_pQueue->hasMessage())
    {
        MessagePtr message = m_pQueue->getMessage();
        qDebug() << "Receive::newMessage " << message->payload;
        if(!m_pQueue->noAck())
        {
            m_pQueue->ack(message);
        }
    } 
}
```

log:

Connection: 
Start
version_major: 0
version_minor: 9
capabilities : FIELD_TABLE 
version :  QVariant(QString, "") 
copyright :  QVariant(QString, "") 
product :  QVariant(QString, "") 
information :  QVariant(QString, "") 
platform :  QVariant(QString, "") 
mechanisms: 
locales: 
Connection: 
Tune
channel_max: 0
frame_max: 131072
heartbeat: 600
Connection: 
OpenOK
Open channel #1
Channel#1:
OpenOK
Declared queue:  "kf.scenechange" 
Message count 0
Consumer count: 0
declared() called... 
Consume ok:  "kf.scenechange" 
Consumer tag = _.scenechange._

**| send message from web console |**

Message create
Receive::newMessage  "test message" 
Message release

**| stop server |**

AMQP: Socket Error:  "The remote host closed the connection" 
AMQP: Socket Error:  "Connection refused" 
AMQP: Socket Error:  "Connection refused" 

**| start server |**

Connection: 
Start
version_major: 0
version_minor: 9
capabilities : FIELD_TABLE 
version :  QVariant(QString, "") 
copyright :  QVariant(QString, "") 
product :  QVariant(QString, "") 
information :  QVariant(QString, "") 
platform :  QVariant(QString, "") 
mechanisms: 
locales: 
Connection: 
Tune
channel_max: 0
frame_max: 131072
heartbeat: 600
Connection: 
OpenOK
**| send message from web console |**
**| and nothing happens|**

**Comment by fuCtor** [comment]
https://github.com/fuCtor/QAMQP/issues/16 maybe it will be usefull.

When client reconnected, declared exchange|queue are not restoring and not rebinding.

**Comment by thefastman** [comment]
thanks a lot , it works now as I expected.
