### ISSUE TITLE
I built the QAMQP Demo in Windows Qt5 successfully,but nothing happen!

### ISSUE THREAD

**Issue by SimplestCode** [fuCtor/QAMQP#20]
Sorry for my poor English..
I built the QAMQP Demo in Windows Qt5 successfully,but when i run nothing happened..
so this program only run in Linux?

**Comment by fuCtor** [comment]
What demo do you compile? Try start demo application with --help.

**Comment by SimplestCode** [comment]
It's ok,i Know how to sue QAMQP,thank you very much!
