### ISSUE TITLE
Why the method cleanup from amqp.cpp file does nothing?

### ISSUE THREAD

**Issue by reypg87** [fuCtor/QAMQP#21]
static inline void cleanup(Client *that, ClientPrivate *d)
    {
# ifdef QT_NO_EXCEPTIONS

```
    Q_UNUSED(that);
    Q_UNUSED(d);
```
# else

```
    Q_UNUSED(that);
    Q_UNUSED(d);    
```
# endif

```
}
```

Indeed is the same code on exceptions enabled or not.

**Comment by fuCtor** [comment]
It was copy/paste =) I rewrite it later.
