### ISSUE TITLE
About ack

### ISSUE THREAD

**Issue by ximply** [fuCtor/QAMQP#23]
My qamqp client info as follow:
Exchange: direct and QAMQP::Exchange::Durable
Queue: ack enabled and QAMQP::Queue::Durable

Now, when I received a message from MQServer but I didn't call this code: [ queue->ack(message); ]
then I cannot get any other messages from MQServer again!

**Comment by ximply** [comment]
Today I try this again, but it didn't reappear , I don't know why?

**Comment by fuCtor** [comment]
I don't work with this server, and dont't make test with it. Sorry.

**Comment by ximply** [comment]
I use amqp_queue.h -> void setNoAck(bool noAck); to disable ack but it doesn't work,.
then I use amqp_queue.h ->  void consume(ConsumeOptions options = ConsumeOptions(NoOptions));
to disable ack  and it works.

**Comment by fuCtor** [comment]
void setNoAck(bool noAck); 
this flag using only with GET method. And it don't sync with consume options.
If you use GET you don't use CONSUME, and if you use CONSUME you don't use GET. It's two different strategy of message processing.

But you can publish sample of code with setNoAck. I'll see it.

**Comment by ximply** [comment]
Oh! I see now, thanks very much.
