### ISSUE TITLE
Отправка сообщения

### ISSUE THREAD

**Issue by and-and-and** [fuCtor/QAMQP#3]
Наверное уже надоел, но никак не получается сделать. Сообщения до этого отправлял вот так:
connect(ui->sendButton, SIGNAL(clicked()), this, SLOT(snd())); 
connect(queue, SIGNAL(declared()), this, SLOT(declared()));
connect(queue, SIGNAL(messageRecieved()), this, SLOT(rcv()));
...
void MainWindow::snd()
{
    exchange->publish(ui->textSendEdit->toPlainText(), exchange->name());
}
void MainWindow::declared()
{
    queue->consume(QAMQP::Queue::coNoAck);
}
void MainWindow::rcv()
{
    ui->textReceiveEdit->append("--> "+QTime::currentTime().toString());
    while (queue->hasMessage())
    {
        QAMQP::MessagePtr message = queue->getMessage();
        ui->textReceiveEdit->append(QString(message->payload));
    }
}
То есть на кнопку нажимаем сообщение отправляется и все работает, но когда хочу сделать тоже самое, но без кнопки и из консоли, ничего не получается. Вызов snd() ни к чему не приводит. Не могли бы вы еще раз подсказать как правильно отправить сообщение? В тестовом примере отправляется только 1 раз и сразу оно же получается, как я понял, то есть немного не то.

**Comment by fuCtor** [comment]
Отправлять можно только тогда, когда Exchange создан, т.е. по сигналу declared. Только тогда сервер готов принимать от клиента сообщения на отправку. Так в тестовом примере как раз отправка происходит когда очередь готова, следовательно на тот момент и Exchange готов. Поэтому вам надо обернуть вызов отправки в слот, который связать с сигналом от Exchange. 

А работает в случае с кнопкой только потому, что к моменту нажатия кнопки уже вся подготовка завершена.

**Comment by and-and-and** [comment]
Большое спасибо еще раз. Примерно так и думал, между созданием, подключением и отправкой вызывал usleep(), но похоже делал это как-то не так в qt, с таймером все получилось :)

**Comment by and-and-and** [comment]
Здравствуйте, если можно подскажите пожалуйста как сделать у сообщений Delivery mode = 2 (Persistent), чтобы после перезапуска сервера сообщения сохранялись в очереди. Когда отправляю через management plugin все работает, есть ли такая опция в QAMQP?

**Comment by fuCtor** [comment]
Да есть такая возможность, но не вынес это в интерфейс. Вечером тогда постараюсь сделать данную модификацию.
Либо при желании можете сами пропатчить: amqp_exchange.cpp строка 224
В этот метод добавить:
content.setProperty(Content::cpDeliveryMode, 2);

**Comment by and-and-and** [comment]
Ох, спасибо большое опять :) Сделал как вы сказали - все работает.

**Comment by fuCtor** [comment]
Только учтите, что теперь все сообщения будет с данным флагом.

**Comment by fuCtor** [comment]
Добавил возможность прокинуть параметры, теперь можно отправлять так:
  QAMQP::Exchange::MessageProperties properties;
  properties[QAMQP::Frame::Content::cpDeliveryMode] = 2; // Make message persistent
  exchange_->publish("123", exchange_->name(), properties);
