### ISSUE TITLE
only "AMQP: Heartbeat" string I see

### ISSUE THREAD

**Issue by lissdx** [fuCtor/QAMQP#32]
Hi.
Thank you for your great job. It is really useful product.
I happened to encounter some strange AMQP behavior ( probably it's my fault ).
The AMQP client works 5-8 hours with no problems and receive MSG. Suddenly 
the client stops receive MSG from server ( the server still have a long queue ) but 
only "AMQP: Heartbeat" string I see in log.

Do you have some suggestion or advice how to fix this problem?

Thank you. Yuri

**Comment by fuCtor** [comment]
It's so strange. Can you see by Wireshark pocket between client server and check state of channel on server? Maybe was reconnect, but you don't make rebind. Check this part too.
