### ISSUE TITLE
Byte order 

### ISSUE THREAD

**Issue by matwey** [fuCtor/QAMQP#6]
AMQP 0.9.1 specification, section 4.2.5.1 states that:

"Integers and string lengths are always unsigned and held in network byte order."

network byte order also known as big-endian, motorolla, etc.

at the same time, in amqp_frame.cpp no attempts are undertaken to handle byte order of integers. How does it works in this way on intel-based machines?

**Comment by fuCtor** [comment]
Big-endian is default order for QDataStream (by documentation).

**Comment by matwey** [comment]
But it doesn't affect readRawData. look at this code snippet:

``` c++
#include <QByteArray>
#include <QDataStream>
#include <QDebug>


int main() {

    QByteArray ba;
    QDataStream ds( &ba, QIODevice::WriteOnly);

    quint32  magic = 0x12345678;

    ds << magic;

    for( int i = 0; i < ba.size(); ++i ) {
        qDebug() << i << hex << int(ba.at(i));
    }

    QDataStream ds2( &ba, QIODevice::ReadOnly);
    char octet4[4] = {0};
    ds2.readRawData(octet4, sizeof(octet4));
    quint32 read = *reinterpret_cast<quint32*>(octet4);

    qDebug() << hex << magic;
    qDebug() << hex << read;

    return 0;
}

```

**Comment by fuCtor** [comment]
Now understand. I think right way will be replace this method on _operator >>_.

I did not see it early, because this case never called.
