### ISSUE TITLE
Как добиться мгновенного "in_queue_->ack(message)"?

### ISSUE THREAD

**Issue by lissdx** [fuCtor/QAMQP#9]
Добрый день.
Спасибо за прекрасный клиент на QT для RabbitMQ.

Если не затруднит, помогите мне. Уже несколько дней не могу
добиться правильной (  для нас ) работы клиента.

Мы бы хотели, чтобы считанное сообщение больше никогда не возвращалось в очередь.
На практике мы убиваем часть незавершенных процессов, часто видем "redelivered msg".
Подскажите, где я допускаю ошибку?

Параметры создания очереди:

in_queue_->declare( QAMQP::Queue::QueueOptions( QAMQP::Queue::Durable )); 
....
    in_queue_->setQOS(0,1);
    in_queue_->consume();
    in_queue_->setNoAck(false);

Считывающий IF:
//-----------------------------------------------------
    if( in_queue_ != NULL && in_queue_->hasMessage() )
    {
        QAMQP::MessagePtr message = in_queue_->getMessage();
        qDebug("+ RECEIVE MESSAGE");
        qDebug("| Exchange-name: %s", qPrintable(message->exchangeName));
        qDebug("| Routing-key: %s", qPrintable(message->routeKey));
        qDebug("| Content-type: %s", qPrintable(message->property[QAMQP::Frame::Content::cpContentType].toString()));
        qDebug("| MSG: %s", qPrintable(message->payload));

```
    if(!in_queue_->noAck())
    {
        in_queue_->ack(message); // почему-то срабатывает не сразу ????????????????
    }            

    QByteArray msgArray = message->payload;

    emit nextMessageReceived( ( const QByteArray& ) msgArray  );     


    qDebug("+ After emit nextMessageReceived ...");            
}
else
{
    emptyQueue_ = true;
}
```

//-----------------------------------------------------

P.S.
Связываю получение nextMessageReceived в главный процесс обработки асинхронно, через очередь ивентов:
QObject::connect( bisQAMQPListener, SIGNAL( nextMessageReceived( const QByteArray&)), urlcapture, SLOT(load( const QByteArray& )), Qt::QueuedConnection );

Хотелось бы так настроить:
in_queue_->ack(message); // почему-то срабатывает не сразу ????????????????
чтобы message, мгновенно получал-бы "ack" и полученное сообщение больше никогда не возвращалось бы в очередь.

**Comment by fuCtor** [comment]
Спасибо за отзыв. Касательно вашей проблемы, не пробовали использовать обычную связь, не через очередь? Вызов метода ack сразу же отправляет данные в буфер сетевого интерфейса.
Тут бы еще для отладки порекомендовал использовать Wireshark. Он умеет показывать AMQP протокол в разобранном виде. Сам им пользовался в процессе работы над клиентом. В нем будет отлично виден порядок прохождения команд. При обычном соединение сигнала со слотом в логе будет видно получение пакета с новым сообщением и сразу же отправка.

Еще вопрос, как получаете сообщения? используете getMessage или consume ?

**Comment by lissdx** [comment]
Как добиться мгновенного "in_queue_->ack(message)"?

Спасибо за быстрый ответ.
Сообщение читаю :
QAMQP::MessagePtr message = in_queue_->getMessage();

consume - насколько я понял, используется единожды, для подключения к очереди нового консюмера.

По поводу прямого подключения ( это очевидно вызов in_queue_->get();  )
пробовал, мгновенной реакции не вызвало вот так выглядит declared():

void bis::BisQAMQPListener::declared()
{
    BIS_LOG4CXX_DEBUG_START();
   qDebug("\t-= BisQAMQPListener Ready =-");

```
in_queue_->setQOS(0,1);
in_queue_->consume();
in_queue_->setNoAck(false);    
in_queue_->get();       
```

}

а так чтение следующего сообщения:

void bis::BisQAMQPListener::getNextMsg(){

```
qDebug ( qPrintable( QString( "%1 %2 %3 bis::BisQAMQPListener::getNextMsg " ).arg( __FILE__ ).arg( __FUNCTION__ ).arg( __LINE__)));

// Synch. process need lock reading
if( in_queue_ != NULL && in_queue_->hasMessage() )
{
    QAMQP::MessagePtr message = in_queue_->getMessage();

    if(!in_queue_->noAck())
    {
        in_queue_->ack(message);
    }            

    QByteArray msgArray = message->payload;

    emit nextMessageReceived( ( const QByteArray& ) msgArray  );     

    qDebug("+ After emit nextMessageReceived ...");            
}
else
{
    emptyQueue_ = true;
}
```

}

Снифер я еще не подключал. Сегодня попробую.
А когда вообще отправлятся сообщение ack на RabbitMQ?
Может фетчить тоже не надо?
in_queue_->setQOS(0,1);

**Comment by fuCtor** [comment]
Сообщение отправляется сразу же, используется не блокирующий сокет.
Про непрямое подключение отпадает, уже увидел что нормально. В предыдущем куске кода не понятно было что за методы в целом. Фетч определяет количество сообщений за раз, и так стоит 1. В целом странно, тут лучше со снифером посмотреть пакеты. 

Вот это точно лишнее:
in_queue_->get();  

Consume уже вызван, сообщение если появятся и так придут. Так что эта можно смело убрать. Точно сказать не могу, надо почитать стандарт, но есть подозрение, что одно и тоже сообщение запрашивается дважды. Первый раз оно приходит по consume, а второй раз сами его попросили ( in_queue_->get(); ). Т.к. стоит флаг ждать подтверждения, то при первом запросе оно из очереди не извлекается до конца.
